### ISSUE TITLE
结合callback和fiber/coroutine

### ISSUE THREAD

**Issue by jiakai1000** [xicilion/fibjs#106]
请教前辈：目前我有一个想法是将callback和coroutine结合起来，因为我的需求是需要在某一个coroutine中做IO多路复用，同时发起多路IO操作，但是我不想创建多个coroutine来实现这个功能。设想基于libuv来做，对uv_write等函数添加阻塞调用的方式：即cb变量为NULL时为阻塞调用，非NULL时为callback通知。
但是只将callback用于IO多路复用，在callback中还是使用阻塞式调用，即fibjs的使用方式。
不知想法是否可行，请指教。

**Comment by xicilion** [comment]
我有个想法就是这个思路，为现有 fibjs 的 async 方法增加最后一个回调参数，有这个参数，则自动切换为回调模式。这个是可以实现的。

**Comment by jiakai1000** [comment]
是的，而且这样可以兼容Node.JS的生态，我正在做。多谢指教。
