### ISSUE TITLE
fibjs编译出错

### ISSUE THREAD

**Issue by ourfeel** [xicilion/fibjs#126]
![image](https://cloud.githubusercontent.com/assets/4400909/12470653/fb581dca-c030-11e5-8b8a-598bab626e62.png)

**Comment by xicilion** [comment]
你的 gcc 版本太高了吧，v8 建议 4.8，太高了，估计谷歌自己都没测试过。

**Comment by ourfeel** [comment]
@xicilion  编译 nodejs 是可以过的

**Comment by xicilion** [comment]
@ourfeel 我拉了 5.1.1 测试，编译是好的。

**Comment by charliexp** [comment]
GCC 4.6好像编译不了V8

**Comment by ourfeel** [comment]
@charliexp  V8 早要求4.8以上

**Comment by xicilion** [comment]
@ourfeel 我用 5.2 也编译了一下，也没有问题。你查一下你的环境看看。
