### ISSUE TITLE
兼容node_modules引入

### ISSUE THREAD

**Issue by ngot** [xicilion/fibjs#128]
希望能够完全兼容利用npm包管理。

方法1：加上启动参数 `-npm`,依赖查找的目录直接改成`node_modules`
方法2：加上启动参数 `-deps dirname`,根据提供的依赖目录去查找

第二种应该感觉更灵活些

**Comment by xicilion** [comment]
已经支持 node_modules 模块。

**Comment by jim4node** [comment]
require 能支持全局模块目录吗?
