### ISSUE TITLE
httpserver创建后直接stop,导致crash

### ISSUE THREAD

**Issue by vickyjam** [xicilion/fibjs#129]
[code]
var http = require('http');
var server = new http.Server('127.0.0.1', 1337, function(){});
server.stop();

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
[test]
$ fibjs test.js
Segmentation fault: 11 (core dumped)

－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－
[version]
os: Darwin Kernel Version 15.5.0
fibjs: 
{
  "fibjs": "0.2.0",
  "git": "v0.2.0-54-gaaf20a3",
  "clang": "7.3",
  "date": "Jun  7 2016 13:32:15",
  "vender": {
    "ev": "4.20",
    "expat": "2.1.0",
    "gd": "2.1.1",
    "jpeg": "8.3",
    "leveldb": "1.17",
    "mongo": "0.7",
    "pcre": "8.21",
    "png": "1.5.4",
    "mbedtls": "2.2.1",
    "snappy": "1.1.2",
    "sqlite": "3.11.0",
    "tiff": "3.9.5",
    "uuid": "1.6.2",
    "v8": "5.3.53",
    "zlib": "1.2.7"
  }
}

**Comment by vickyjam** [comment]
应该是stop有问题，我run了后再stop仍然crash。

var http = require('http');
var coroutine = require('coroutine');
var server = new http.Server('127.0.0.1', 1337, function() {});

server.asyncRun();
coroutine.sleep(500);
server.stop();

**Comment by vickyjam** [comment]
var http = require('http');
var coroutine = require('coroutine');
var server = new http.Server('127.0.0.1', 1337, function() {});

coroutine.start(function() {
	coroutine.sleep(500);
	server.stop();
})
server.run();

**Comment by xicilion** [comment]
已修复。

**Comment by vickyjam** [comment]
⭐️⭐️⭐️⭐️⭐️
