### ISSUE TITLE
建议为gd模块添加输出图像RAW数据的方法

### ISSUE THREAD

**Issue by AkimotoAkari** [xicilion/fibjs#141]

**Comment by asionius** [comment]
通过gd.load把图像数据加载进来在用image.getData()来得到图像的数据 不知这样能否解决你的需求

**Comment by AkimotoAkari** [comment]
这个得到的虽然是图像数据但是扔给js处理十分麻烦（需要解码），通常需要的是类似于<CanvasContext>.getImageData()这样的返回。

**Comment by xicilion** [comment]
你是不是说想要输出 raw 格式的文件？

**Comment by AkimotoAkari** [comment]
对，类似这样

**Comment by xicilion** [comment]
这个其实意义不大，因为 gd 的图像，来源是 bmp/jpg/png，本身就是 rgb 数据，并没有 raw 的更多数据，如果担心 jpg 损失数据，或者 bmp 尺寸较大的话，可以使用 png 格式输出，既不损失色彩，也会压缩文件尺寸。

**Comment by AkimotoAkari** [comment]
其实就是输出RGB数据(raw pixel data)给js端使用，似乎libpng可以导出？

**Comment by xicilion** [comment]
导出 RGB 是可以的，但是如果是像素级操作，为什么不直接用 pixel 函数呢？什么场景下需要用 raw rgb 进行处理呢？

**Comment by AkimotoAkari** [comment]
用getPixel()方法会导致频繁在js和native间切换降低性能。需要raw rgb的场合，我目前涉及到的有大津法求阈值，以及图像hash

**Comment by xicilion** [comment]
了解了。

**Comment by AkimotoAkari** [comment]
thx

**Comment by xicilion** [comment]
这几天在集中测试准备发布新版本号，过了这段我来看看把这个接口搞一下。

**Comment by AkimotoAkari** [comment]
辛苦了！
