### ISSUE TITLE
一个拼写错误：`colum`

### ISSUE THREAD

**Issue by AkimotoAkari** [xicilion/fibjs#144]
`sprintf(msg, "XmlParser: error on line %lu at colum %lu: %s", XML_GetCurrentLineNumber(xml_parser),`
at fibjs/src/xml/XmlParser.cpp:217
`colum`应为`column`

**Comment by xicilion** [comment]
好细心哈哈，已修正

**Comment by xicilion** [comment]
好细心哈哈，已修正

**Comment by xicilion** [comment]
好细心哈哈，已修正
