### ISSUE TITLE
是否会添加多线程与ffi支持？

### ISSUE THREAD

**Issue by AkimotoAkari** [xicilion/fibjs#154]
对于js端的CPU密集型处理协程与vm都无能为力；fibjs的可执行文件对于大部分项目来说确实有点大。

**Comment by ngot** [comment]
多线程已经支持了

**Comment by AkimotoAkari** [comment]
如何启用？

**Comment by asionius** [comment]
貌似rpc task可以考虑？

**Comment by AkimotoAkari** [comment]
另外有一个建议就是发行fibjs的动态链接库版本

**Comment by asionius** [comment]
@AkimotoAkari 
hi AkimotoAkari 动态库版正在路上

**Comment by xicilion** [comment]
动态链接版本也小不了很多，v8 自己就 10M+ 了。

**Comment by AkimotoAkari** [comment]
谢谢，我正研究rpcTask，希望可以看到fibjsmt.dll
