### ISSUE TITLE
源码中 vender\SpiderMonkey 是做什么用的？

### ISSUE THREAD

**Issue by gmxyb** [xicilion/fibjs#155]
貌似只在工程文件中有，没看有到 fibjs 中使用呢。。

**Comment by Hi-Rube** [comment]
@gmxyb js引擎啊，做实验用的吧

**Comment by ngot** [comment]
板子中用的

**Comment by xicilion** [comment]
还在封装，所以还在试验阶段，没投入使用。

**Comment by gmxyb** [comment]
SpiderMonkey 比V8有其独特的优势么？。。

**Comment by xicilion** [comment]
一、小，spider 编译出来只有 1M，而 v8 要 10M+
二、省内存，同上
三、解释执行，如 iOS，因为安全原因，禁止了 jit，因此 v8 是不能运行的，可以用 spider

**Comment by gmxyb** [comment]
SpiderMonkey不知道是否活跃？会不会跟不上时代呢。。

**Comment by xicilion** [comment]
spider 本身是很活跃的。但是 fibjs 嵌入的这个版本并不是最新的版本。
因为 fibjs 需要对 js 引擎做相应的改造，以支持 fiber 模式运行，更新版本的 spider 没有改造的基础，只好做此选择。
JavaScriptCore 也是因为同样的原因，没法改造为运行 fiber 的模式。
