### ISSUE TITLE
连接mysql时密码存在特殊字符报错

### ISSUE THREAD

**Issue by longly** [xicilion/fibjs#158]
`
var db = require("db");

//#号貌似有问题
var mysql = db.openMySQL("mysql://user:n#xgEr38zeaM@127.0.0.1/db");
var rs = mysql.execute("select count(1) from ddd");
console.log(rs)
`

**Comment by longly** [comment]
`
"use strict"

var db = require("db");
var net = require("net");

var u = new net.Url();
 
var ss =  u.format({
	protocol:"mysql",
	username:"username",
	password:"n#xgEr38zeaM",
	hostname:"127.0.0.1",
	port:"3306",
	pathname:"db1"
});

var mysql = db.openMySQL(u.toString());
`

**Comment by asionius** [comment]
赞

**Comment by asionius** [comment]
因为#是锚点，另外还有？等特殊字符都需要用这种方法
