### ISSUE TITLE
fibjs有没有一些计划任务的库？

### ISSUE THREAD

**Issue by wf744** [xicilion/fibjs#163]
比如说使用fibjs来进行游戏开发，那么游戏里面有一些需要定时运行的任务，比如每天9点要结算排行榜之类的任务，或者说每周六晚上10点进行活动结算，发放奖励之类的需求

**Comment by asionius** [comment]
fibjs目前没有这样的库，但是你可以利用fibjs的定时器来写一个。
很多其他语言都结合crontab来实现计划任务。你也可以通过crontab和fibjs搭配来实现，方法多样、便捷。

**Comment by xicilion** [comment]
npm install crontab
