### ISSUE TITLE
fibjs可以热更新代码么？

### ISSUE THREAD

**Issue by wf744** [xicilion/fibjs#164]
用于游戏的客户端长连接热更新，nodejs可以在tcp socket长连接时进行清理require的缓存中的代码，然后进行重新require来实现热更新，fibjs可以做到吗？

**Comment by ngot** [comment]
首先node.js并不能热更新，清理require缓存，无法关闭很多文件句柄的，所以目前没有办法做到。

fibjs的sandbox可以做到真真的热更新。
