### ISSUE TITLE
语言生态

### ISSUE THREAD

**Issue by slclub** [xicilion/fibjs#170]
一个语言的优秀，
我想现在来说并不是它本身了，
要建立起它强大的生态系统；

node 的npm吗
go的godoc 等

我没看到你的生态系统如何搞和说明；

另外我也觉得要发展起来不是不可能；需要有人给投钱；做一下生态；推广；以及语言本身的优化；需要不少人力物力；

**Comment by slclub** [comment]
我想或许直接用npm 自己搞个服务器，改下名npm名字，关联下github仓库文档。 对你这或许不是很难的工作。但是有了，我想效果应该会有不少进步的。

**Comment by Hi-Rube** [comment]
= =

**Comment by xicilion** [comment]
可以直接用大部分 npm 模块，但不是全部。

**Comment by wf744** [comment]
我觉得fibjs的模型是非常好的，性能很高，但是由于生态和推广策略的问题导致发展得比较慢，我觉得如果可以的话，先瞄准细分领域，比如web开发或者游戏服务器开发，来专攻一个细分领域，做到这个细分领域的前三，相对一个大而全的方向来说更加容易取得成绩

**Comment by slclub** [comment]
还应该找一些投资人，做为支持；阿里等这些主机服务商，都有相应的服务器支持政策吧；还有oschina 对这些东西都是比较支持的，如果能拉来投资可以专注于做这个语言生态就更好了；
要比过golang性能；还能支持动态库；那就棒棒的了啊

**Comment by slclub** [comment]
npm ：一些扩展  常用命令 你可以叫它jpm
   update
   version controll

**Comment by dsonet** [comment]
> 可以直接用大部分 npm 模块，但不是全部。

How to determine which one can be supported and which one can't, what's the specific condition?
