### ISSUE TITLE
心路历程

### ISSUE THREAD

**Issue by u0024window** [xicilion/fibjs#173]
可以写一下开发fibJS的心路历程吗，或者对这个项目的简介，博客之类的，这样会激发更多的人为这个项目作出贡献

**Comment by u0024window** [comment]
有QQ群或者微信交流群吗

**Comment by ngot** [comment]
https://github.com/ngot/blog/issues/1

**Comment by Hi-Rube** [comment]
@u0024window 可以让 @xicilion 拉群

**Comment by xicilion** [comment]
加我微信 xicilion，注明 fibjs，我拉你入群。
