### ISSUE TITLE
Can't Build with Visual Studio 2017(RC)?

### ISSUE THREAD

**Issue by EtaoinWu** [xicilion/fibjs#176]
The project file could not be built with VS 2017 RC.
I tried both build.bat and *.sln but it gives `Can't find include file "windows.h"` and etc.

**Comment by xicilion** [comment]
It's ok. Did you installed windows SDK?

**Comment by EtaoinWu** [comment]
@xicilion actually the sln file requires the windows SDK version 7.0 but VS17 doesn't include it. After changing it into version 10.0.* it will be ok.
