### ISSUE TITLE
Hard to understand Doc.

### ISSUE THREAD

**Issue by fizerkhan** [xicilion/fibjs#30]
Need an English version of Documentation.

**Comment by dayuoba** [comment]
深入了解fibjs后愿意加入利用空余时间 为fibjs做些力所能及的贡献，刚开始关注fibjs。
同时想请教一下关于fibjs发展方向的问题。

**Comment by xicilion** [comment]
fibjs 目前阶段处于稳定时期，主要的工作是修改 bug，完善文档，增加和固定基础接口。

下一阶段会开始考虑分布式计算框架。
