### ISSUE TITLE
将 Function::start(...) 给定为不推荐使用

### ISSUE THREAD

**Issue by overminder** [xicilion/fibjs#36]
考虑到 `coroutine.start(func, ...)` 已经有这个功能了，另外修改 `Function.prototype` 感觉还是有点不够严谨，再说了 `someFunction.start` 看起来也不够扎眼（不仅仅是人眼，还有静态检查器）.. 能否将 `coroutine.start(func, ...)` 定为推荐使用方式，而将 `Function::start` 逐步淡出呢？

当然也并不是说 `Function::start(...)` 非常的不好，fibjs 作为一个语言层面上的 coroutine 实现，和原本的 js 有些不同也是完全可以接受的。我只是感觉从一个语法的角度上来看，可能有更好的方法。

# English Translation
## Deprecate `Function::start(...)`
Since we have already got `coroutine.start(func, ...)`, I think maybe we could deprecate `Function::start(...)`. The former can be identified in the code and analyzed by static checkers more easily. Another reason is that I don't like the way that the latter is implemented (by modifying a builtin type's prototype).

**Comment by dsonet** [comment]
@overminder +1. Semantically Function::start also not easy to understand, I agree to deprecate it. 
仅从语义上来说，coroutine.start(func, ...) 比 Function::start 要更容易理解。因此赞成废弃后者。

**Comment by xicilion** [comment]
已进入废弃程序。
