### ISSUE TITLE
Buffer new 或者 write 数组的问题

### ISSUE THREAD

**Issue by illuspas** [xicilion/fibjs#44]
var a = new Buffer([0x01,0x02,0x03]);
var b = new Buffer([0x04,0x05,0x06]);
var c = new Buffer([a,b]); // new 或者write操作，传入Buffer数组
console.log(c.length); // 7
console.log(c.hex()); // 0102032c040506
数组的连接符被当做数据赋值了

**Comment by xicilion** [comment]
没有太明白

**Comment by illuspas** [comment]
其实是想使用类似Node中 Buffer.concat()这样的方法合并多个Buffer对象
目前fibjs没这方法
于是我就直接把多个Buffer对象放在数组里面作为参数来new一个Buffer

**Comment by jiangzhuo** [comment]
> var a = new Buffer([0x01,0x02,0x03]);
> var b = new Buffer([0x04,0x05,0x06]);
> var c=new Buffer();
> c.write(a)
> c.write(b)
> console.log(c.length)
6
> console.log(c.hex());
010203040506

@illuspas 
文檔上那個傳Array的構造函數 不是你這個意思。。

**Comment by illuspas** [comment]
我的意思是：傳Array的構造函數 能不能就是我這個意思。。

**Comment by jiangzhuo** [comment]
那就不是構造函數的問題了
那是需要修改Array的構造函數了，比如說改成：
    在兩個參數都是Buffer的情況，把Buffer內的內容按順序拼成一個Array
這顯然不行啊

**Comment by illuspas** [comment]
好吧，其实Node里也不能这么构造 
要不然就实现 Buffer.concat 这个类方法 以前用node写的程序移植起来就更简单了

**Comment by ngot** [comment]
@illuspas 我来尝试加 Buffer.concat

**Comment by R32** [comment]
我发现 write(Array data)时,只是简单调用了 toString,这样的话这个重载似乎没什么意义,

我感觉 Buffer 的很多地方都不对,相比较nodejs 1)它不应该建立在 std::string 下,它应该是个固定数组,这样的话 write 和 writeXXXX 应该一致,不允许调整尺寸, 2) 移除 resize, 3) 就大数语言的规范,slice 并不会修改原对象,nodejs 也符合,它返回的Buffer是建立在原Buffer上的引用, 修改原对象的应该叫 splice, 还有 slice 的第二个参数 end为负数时,和 str.slice 处理的不一致

**Comment by xicilion** [comment]
Buffer 的一些实现的确与 nodejs 不兼容，这部分已经安排计划在修改了，多谢关注。
