### ISSUE TITLE
编译出错，谁知道原因呀

### ISSUE THREAD

**Issue by johe11** [xicilion/fibjs#59]
环境：
OS：Centos 6.5 32位

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/i686-pc-linux-gnu/4.8.3/lto-wrapper
Target: i686-pc-linux-gnu
Configured with: ./configure --prefix=/usr --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 4.8.3 (GCC) 

cmake --version
cmake version 2.8.12.2

make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-redhat-linux-gnu

出错的文件
[ 17%] Building CXX object CMakeFiles/fibjs.dir/src/ssl/SslSocket.cpp.o
/home/weixin/fibjs/fibjs/src/ssl/SslSocket.cpp: In destructor 鈥榲irtual fibjs::SslSocket::~SslSocket()鈥?
/home/weixin/fibjs/fibjs/src/ssl/SslSocket.cpp:90:36: error: 鈥榤emset鈥?was not declared in this scope
     memset(&m_ssl, 0, sizeof(m_ssl));
                                    ^
/home/weixin/fibjs/fibjs/src/ssl/SslSocket.cpp: In member function 鈥榠nt fibjs::SslSocket::my_recv(unsigned char*, size_t)鈥?
/home/weixin/fibjs/fibjs/src/ssl/SslSocket.cpp:134:49: error: 鈥榤emcpy鈥?was not declared in this scope
     memcpy(buf, m_recv.c_str() + m_recv_pos, len);
                                                 ^
make[2]: *** [CMakeFiles/fibjs.dir/src/ssl/SslSocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/fibjs.dir/all] Error 2
make: *** [all] Error 2

已经编译了几编了

**Comment by verdantyang** [comment]
我在ubuntu下也发现了这个问题，mac下没遇到过
这几个文件加个#include "string.h"试试
   fibjs/src/ssl/SslSocket.cpp
   fibjs/src/crypto/Cipher.cpp
   fibjs/src/crypto/crypto.cpp

**Comment by xicilion** [comment]
才看到这个问题，是升级 ssl 库引入的，已修复。
