### ISSUE TITLE
OSX 编译无效

### ISSUE THREAD

**Issue by LuoZijun** [xicilion/fibjs#67]
请问 OSX 系统要如何编译呢？
我在编译时 是这样的: 

![image](https://cloud.githubusercontent.com/assets/717717/8509992/d778e510-22fb-11e5-8348-b81ec86be3b0.png)

**Comment by mediapig** [comment]
看之前的说明。你少操作了

**Comment by LuoZijun** [comment]
@mediapig 能告知在何处可以看到 你说的｀说明｀吗？

**Comment by BeaverCC** [comment]
请仔细看下readme

**Comment by xicilion** [comment]
sh build Release -j

**Comment by LuoZijun** [comment]
@xicilion hi, -j 不是启用多 进程/线程的 意思吗？ 原来是这样，看来我理解错了。回家我再试下。

**Comment by LuoZijun** [comment]
@xicilion hi, 我试了，发现还是不行呢，这个到底能否在 OS X 下面编译呢 ?
![72ea6e08-ed6f-445f-b046-aa8c38924310](https://cloud.githubusercontent.com/assets/717717/8603336/158682ac-26aa-11e5-9e33-518b48661dca.png)

**Comment by verdantyang** [comment]
OS X下是可以编译通过的
  1)编译之前有没有把vender和docs子模块加入项目呢？
  $ git submodule update
  2)检查一下文件编码
  $ vim build
  :set ff 查看是否是fileformat=unix，如果不是执行:set ff=unix

**Comment by LuoZijun** [comment]
@verdantyang 非常感谢，的确是我没有 把子模块加入进来造成的，要是能有个提示就好了。
