### ISSUE TITLE
fibjs是否可以放开V8垃圾回收并行sweeper？

### ISSUE THREAD

**Issue by yjhjstz** [xicilion/fibjs#70]
并行sweeper和主线程无关，和fiber应该也没有关系，可以考虑放开，而不是现在的fiber切换。
@xicilion

**Comment by xicilion** [comment]
v8 的工作也需要使用锁。目前 fibjs 的 fiber 锁还不支持非 fiber 线程操作，所以暂时还不能 fiber 和 thread 混用。

**Comment by yjhjstz** [comment]
是的，但还是可以区分开。需要修改V8.

**Comment by xicilion** [comment]
区分和改造本身 fibjs 已经就做了。唯一的障碍就是要改造 fiber 的锁，允许普通 thread 混用。这个有些复杂，要花些功夫。

**Comment by xicilion** [comment]
花了一个星期把这事干成了。哈哈
