### ISSUE TITLE
Fibjs的内存使用限制

### ISSUE THREAD

**Issue by LuoZijun** [xicilion/fibjs#79]
最近，我分别在Rust/Golang/Swift/Ocaml/Python/PHP这几个语言里面测试了 存储一个有 1 0000 0000 个整数列表 ，分别需要多大的空间。

Rust 表现最好，只需要300MB.
Golang 需要734MB.
Swift 需要 1GB.
Python 需要 3GB.
PHP 需要 13.75GB内存..... ( 并且执行时间超过 20秒, python 只需要 2秒 )

以下是 Fibjs 的内存占用，截至程序崩溃，fibjs 需要内存 530 多 MB.

不知道是 V8引擎的问题还是fibjs的问题。

    ➜  Linux_Release git:(master) ./fibjs test_mem.js 

    <--- Last few GCs --->

        1140 ms: Mark-sweep 958.4 (995.3) -> 575.9 (612.8) MB, 77.3 / 0 ms (+ 0.0 ms in 1 steps since start of marking, biggest step 0.0 ms) [allocation failure] [GC in old space requested].
        1241 ms: Mark-sweep 575.9 (612.8) -> 575.9 (612.8) MB, 100.7 / 0 ms [allocation failure] [GC in old space requested].
        1337 ms: Mark-sweep 575.9 (612.8) -> 575.9 (612.8) MB, 96.3 / 0 ms [last resort gc].
        1439 ms: Mark-sweep 575.9 (612.8) -> 575.9 (612.8) MB, 101.5 / 0 ms [last resort gc].

    <--- JS stacktrace --->

    ==== JS stack trace =========================================

    Security context: 0x1c94a4e36619 <JS Object>
        2: /* anonymous */ [test_mem.js:~1] [pc=0x31515ea7784a] (this=0x2f3f38c9e869 <an Object with map 0x2660c25065c9>,require=0x2f3f38c10ec9 <JS Function (SharedFunctionInfo 0x2f3f38c10e39)>,run=0x2f3f38c11069 <JS Function (SharedFunctionInfo 0x2f3f38c10fd9)>)

    ==== Details ================================================

    [2]: /* anonymous */ [test_mem.js:~1] [pc=0x31515ea7784a] (this=0x2f3f38c...

    #
    # Fatal error in CALL_AND_RETRY_LAST
    # Allocation failed - process out of memory
    #

![2015-08-08 14 31 29](https://cloud.githubusercontent.com/assets/717717/9149418/8f19f638-3ddb-11e5-9356-3c5d91787814.png)

**Comment by LuoZijun** [comment]
哦，忘了补上 ocaml.
ocaml 在解释器上面消耗内存 2.3GB.
经过编译后 消耗内存 1.7GB.

**Comment by xicilion** [comment]
这个应该是 v8 的限制。测试脚本是什么？你试一下 --max_old_space_size 参数。帮助参数 --help。

**Comment by LuoZijun** [comment]
@xicilion 测试脚本是这个 https://github.com/LuoZijun/memtest/blob/master/src/fibjs.js
 你说的这个参数我去公司的时候 再试下。自己电脑内存有限不敢试。到时候会和NodeJS 做一个比较.

**Comment by xicilion** [comment]
```
var os = require("os");

var mem1 = os.memoryUsage().heapUsed;

var data = [];
for (var i = 0; i < 100000000; i++) {
	data.push(i);
}
console.log("Length: " + data.length);
console.log("memory usage:", os.memoryUsage().heapUsed - mem1);
```
执行结果如下：
```
fibjs t.js --max_old_space_size=8192
Length: 100000000
memory usage: 2469341648
```
node 不支持这个参数，测试失败。

**Comment by xicilion** [comment]
js 的数组是 Number，这样比较比较吃亏，你可以用 Int16Array，
```
var data = new Int16Array(100000000);

for (var i = 0; i < 100000000; i++) {
	data[i] = i;
}
console.log("Length: " + data.length);
console.readLine();
```
跑完加上 fibjs 自己的空间才 199MB。

**Comment by LuoZijun** [comment]
@xicilion 有点意外，即便是Number这种模糊的整数类型，2GB多的内存其实也不大了。Ocaml的这种类型也是模糊的，内存消耗比起JS就好一点。而其他的几个靠前的都是强类型语言，确实没有可比性。

另外，这个 --max_old_space_size=8192 是否能够默认开启的呢？
而不需要手动在运行的时候开启？编译的时候是否有相关参数呢？

**Comment by xicilion** [comment]
这个不是常用需求，手动就好了吧。如果自己编译的话，修改一下 base/options.cpp 里面的预设参数。

**Comment by LuoZijun** [comment]
@xicilion ok :)
