### ISSUE TITLE
json 支持

### ISSUE THREAD

**Issue by LuoZijun** [xicilion/fibjs#97]
@xicilion 目前使用 Fibjs 内建的 HTTP 模块创建的 HTTP Server 是不是不支持识别 客户端传送过来的    `Content-Type` 呢？目前似乎在 客户端的 request 里面指定 `body` 数据的格式是 'application/json' 就直接出错误哦。 
![json](https://cloud.githubusercontent.com/assets/717717/9868149/2579ae18-5ba8-11e5-83e1-11c4ed3f8729.png)

另外， 要怎么读取出 这个 request 的 http body 段的原内容呢？这样的话，可以自己解析。

**Comment by xicilion** [comment]
request.body.readAll().toString()

**Comment by LuoZijun** [comment]
@xicilion 使用你说的这个 `request.body.readAll().toString()` 好像不行。

**代码**

```js
var http = require('http');
var mq = require('mq');

var application = function (req){
    var protocol = req.protocol;
    var method = req.method;
    var request_uri = req.address;
    var query_string = req.queryString;

    var headers = req.headers.toJSON();
    var cookies = req.cookies.toJSON();
    // content-type 支持有问题，目前不支持 application/json
    var form = req.form.toJSON();

    // *** HTTP BODY ***
    var body = req.body.readAll().toString();
    var body_size = req.length;

    var remote_port = req.stream.remotePort;
    var remote_address = req.stream.remoteAddress;
    var local_port = req.stream.localPort;
    var local_address = req.stream.localAddress;

    console.log( body );
};

var server = new http.Server(8080, application);
server.run();
```

**HTTP Request**

```bash
curl -X PUT -d '{"uuuu":"34564p910521"}' "http://127.0.0.1:8080/path1/cgi.py?pwd=3465&abc=bbc" -H 'TEST: ASDAS'

```

**错误提示**
>    HttpHandler: TypeError: Cannot read property 'toString' of null at application (app.js:17:34)

**Comment by xicilion** [comment]
你之前成功获取过 form，所以 body 内容已经被读取出来了。如果你还想重读，可以先 req.body.rewind();

**Comment by LuoZijun** [comment]
@xicilion 谢谢。
另外一个问题，由于我自己需要去 `headers` 里面读取 `content-type` ，但是 底层实现似乎没有考虑大小写问题，也没有对数据进行修整。所以我必须得先在 js 里面遍历所有的 `key` 才能取到我想要的 'content-type' 的值。

对于这个问题，能否在底层 比如统一小写，或者 首字母大写呢 ？
:))

**Comment by LuoZijun** [comment]
@xicilion 不对哦，读取了 `form` 之后，再使用 `req.body.rewind();` 重读 返回的是 `undefined` .

**Comment by xicilion** [comment]
req.body.rewind() 不是读操作，是指针复位操作，之后再用 readAll 读取。
headers 查询是不区分大小写的，你测一下。

**Comment by xicilion** [comment]
你区分了大小写，是因为你把 header toJSON 转换成 JS 的 Object 了。

**Comment by LuoZijun** [comment]
@xicilion Thx.
