### ISSUE TITLE
必须点赞。。。

### ISSUE THREAD

**Issue by imfly** [xicilion/fibjs#98]
之前一直玩`ruby on rails`，最近因为项目需要，用了`nodejs`，大概有一个月了。对于nodejs蹩脚的回调，还有调试的不友好，感觉很失望。于是，找到了这里。

我个人觉得，`fibjs`是很有希望的项目。发展起来之后，在js语言开发领域，就与nodejs，io.js并驾齐驱，给了开发者另一个很好的选择。

中国人，做技术的人很多，优秀的人也很多，但重量级的很少，干脆说没有。我觉得，个中原因就是浮躁，害怕失败。从这个角度，作者 @xicilion 响马，值得俺学习。

看看小日本，几乎每个优秀的开源项目，在支持英文的同时，另一种语言就是日文。ruby也是小日本搞起来的，最初几年同样全是批评的声音，直到rails的出现，才真正火了起来。

优秀是一种品质。失败的产品多种多样，成功的产品都具有共同的特点：完善的文档、简单的开发调试方法、优秀的扩展机制，这些足可以让社区自我复制和发展，当然如果有兼容其他已有资源的特点，或类似rails的伟大应用实例，更有引爆社区的力量。

`fibjs`可能还有很长一段路要走，但是只要有了起点，终点就一定不会远。

先`fork`了，看我能做些什么？

**Comment by xicilion** [comment]
哎呀这么高的评价哈哈，感谢关注，你们的鼓励是我们前进的动力。
